In [28]:
a=int(input)
for a in input:
    a**a
print(a)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'method'

In [2]:
x=[]
a=int(input(""))
for i in range(1,a+1):
    x.append(i**2)
print(x)
    

5
[1, 4, 9, 16, 25]


In [5]:
x=[]
a=int(input(""))
for i in range(1,a+1):
    x.append(i-2)
print(x)

9
[-1, 0, 1, 2, 3, 4, 5, 6, 7]


In [8]:
a=[]
x=int(input(""))
for i in range(1,x+1):
    a.append(i-2)
print(a)

9
[-1, 0, 1, 2, 3, 4, 5, 6, 7]


In [9]:
import numpy as np

In [11]:
x=[]
a=int(input(""))
for i in range(1,a+1):
    x.append(i*i)
print(x)

5
[1, 4, 9, 16, 25]


In [14]:
a=int(input(""))
a=3.14*(3*3)
print(a)

8
28.26


In [15]:
r=int(input(""))
import math
a=math.pi
area=a*(r**2)
print(area)

3
28.274333882308138


In [23]:
for i in  range(4+1):
    print(i*" * ")
    print(end="")


 * 
 *  * 
 *  *  * 
 *  *  *  * 


In [13]:
c=float(input())
r=float(input())
if c <=0.051:
    if r <=14.98:
        print("benign")
    else:
        print("malignant")
else:
    if r <=11.345:
        print("benign")
    else:
        print("malignant")

0.02
11.0
benign


In [3]:
a=7
b=5
c=(a*a+b*b)**(1/2)
print(c)

8.602325267042627


In [4]:
import math
c=math.sqrt(a*a+b*b)
c

8.602325267042627

In [21]:
for i in range(7):
    print(i*"*")
    print(end="")


*
**
***
****
*****
******


In [ ]:
for i

In [34]:
n=int(input())
for i in range(4):
    print(i,"*")
    print(end="")

5
0 *
1 *
2 *
3 *


In [2]:
class UserMainCode(object):
    @classmethod
    def capitalize(cls,input1):
        print(input1)
        a=input1.title()
        print(a)
        return a
        

In [6]:
def capitalize(cls,input1):
        print(input1)
        a=input1.title()
        print(a)
        return a

In [7]:
capitalize(object,"he is a boy")

he is a boy
He Is A Boy


'He Is A Boy'

In [10]:
class UserMainCode(object):
    @classmethod
    def capitalise(cls,input1):
        print(input1)
        a=input1.capitalize()
        print(a)
        return a

In [12]:
def capitalise(cls,input1):
        print(input1)
        a=input1.capitalize()
        print(a)
        return a

In [26]:
def capitalize(cls,input1):
    print(input1)
    a=input1.capitalize()
    print(a)
    return a

In [13]:
capitalise(object,"he is a boy")

he is a boy
He is a boy


'He is a boy'

In [20]:
n=int(input())
import numpy as np
a=np.zeros([n,n],int)
a[0]=a[n-1]=1
b=1
for i in range(1,n-1):
    a[i][b]=1
    b=b+1
print(a)
    

5
[[1 1 1 1 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 1 1 1 1]]


In [49]:
class UserMainCode(object):
    @classmethod
    def capitalise(cls,n):
        a=np.zeros([n,n],int)
        a[0]=a[n-1]=1
        b=1
        for i in range(1,n-1):
            a[i][b]=1
            b=b+1
        print(a)
        return a
        

In [50]:
def capitalise(cls,n):
        a=np.zeros([n,n],int)
        a[0]=a[n-1]=1
        b=1
        for i in range(1,n-1):
            a[i][b]=1
            b=b+1
        print(a)
        return a

In [25]:
capitalise(object,5)

[[1 1 1 1 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 1 1 1 1]]


array([[1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1]])

In [27]:
a=[1,3,4,7,5]
b=4
c=0
for i in a:
  if i>b:
    c=c+1
print(c)

2


In [35]:
def List(a):
    x=[]
    for i in a :
        x.append(i)
    return x

In [36]:
List((1,2,3,4,5))

[1, 2, 3, 4, 5]

In [59]:
def shape(a):
    for i in range(1,a+1):
        for j in range(1,i+1):
            print(j,end="")

In [62]:
shape(4)

1121231234

In [80]:
def shape(a):
    x=[]
    for i in range(1,a+1):
        for j in range(1,i+1):
            print(j,end="")
        print(j)

In [82]:
shape(5)

11
122
1233
12344
123455


In [57]:
def List(a):
    x=[]
    for i in a:
        x.append(i)
    return x

In [58]:
List((5,6,7,8,9))

[5, 6, 7, 8, 9]

In [88]:
def chair(a):
    x=[]
    for i in range(1,a+1):
        for j in range(1,i+1):
            print(j,end="")
        print()
    for i in range(a-1,0,-1):
        for j in range(1,i+1):
            print(j,end="")
        print()

In [92]:
chair(3)

1
12
123
12
1


In [94]:
a=20
b=10
if a>b:
    c=b
elif a<b:
    c=a
else:
    print(a)
for i in range(1,c+1):
    if(a%i==0) and (b%i==0):
        gcd=i
print(gcd)

10


In [8]:
n=int(input())
import numpy as np
a=np.zeros([n,n],int)
a[0]=a[n-1]=1
b=1
for i in range(1,n-1):
    a[i][b]=1
    b=b+1
print(a)

6
[[1 1 1 1 1 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [1 1 1 1 1 1]]


In [9]:
n=int(input())
import numpy as np
a=np.zeros([n,n],int)
a[0]=a[n-1]=1
b=1
for i in range(1,n-1):
    a[i][b]=1
    b=b+1
print(a)

5
[[1 1 1 1 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [1 1 1 1 1]]


In [10]:
n=int(input())
import numpy as np
a=np.zeros([n,n],int)
a[0]=a[n-1]=1
b=1
for i in range(1,n-1):
    a[i][b]=1
    b=b+1
print(a)

4
[[1 1 1 1]
 [0 1 0 0]
 [0 0 1 0]
 [1 1 1 1]]


In [12]:
n=int(input())
import numpy as np
a=np.zeros([n,n],int)
a[0]=a[n-1]=1
b=1
for i in range(1,n-1):
    a[i][b]=1
    b=b+1
print(a)

3
[[1 1 1]
 [0 1 0]
 [1 1 1]]


In [9]:
for i in range(4):
    for j in range(4):
        if (i == 1 or i == 2) and (j == 1 or j == 2):
            print(1, end ="")
        else:
            print(0, end ="")
    print()

0000
0110
0110
0000


In [14]:
n=int(input())
import numpy as np
a=np.zeros([n,n],int)
a[0]=a[n-1]=1
b=1
for i in range(1,n-1):
    a[i][b]=1
    b=b+1
print(a)

3
[[1 1 1]
 [0 1 0]
 [1 1 1]]


In [26]:
def capitalize(cls,input1):
    print(input1)
    a=input1.capitalize()
    print(a)
    return a

In [28]:
capitalize(object,"are you mad?")

are you mad?
Are you mad?


'Are you mad?'

In [35]:
def capitalize(cls,input1):
    print(input1)
    a=input1.title()
    print(a)
    return a

In [36]:
capitalize(object,"are you dude?")

are you dude?
Are You Dude?


'Are You Dude?'

In [39]:
def capitalize(cls,input1):
    print(input1)
    a=input1.title()
    print(a)
    return a

In [41]:
capitalize(object,"free coupon")

free coupon
Free Coupon


'Free Coupon'

In [42]:
def capitalize(cls,input1):
    print(input1)
    a=input1.capitalize()
    print(a)
    return a

In [43]:
capitalize(object,"free coupon")

free coupon
Free coupon


'Free coupon'

In [44]:
n=int(input())
for i in range(n):
    for j in range(i+1):
        print(j+i,end=" ")
    print()

4
0 
1 2 
2 3 4 
3 4 5 6 


In [47]:
n=int(input())
for i in range(n):
    for j in range(i+1):
        print(j+1,end="")
    print()

3
1
12
123


In [48]:
n=int(input())
for i in range(n):
    print(i*"*")
    print(end="")

3

*
**
